services:
  app-db:
    image: postgres:16
    container_name: sikili_app_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: sikili_sync
    ports:
      - "5433:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data

  odoo-db:
    image: postgres:16
    container_name: sikili_odoo_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    container_name: sikili_odoo
    depends_on:
      - odoo-db
    ports:
      - "8069:8069"
    environment:
      HOST: odoo-db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons

volumes:
  app_db_data:
  odoo_db_data:
  odoo_data:
